### ISSUE TITLE
Setting

### ISSUE THREAD

**Issue by Lucifer0601code** [Dovakiin0/animeworldz-mobile#1]
add plenty of features

**Comment by Dovakiin0** [comment]
Can you specify what features would you want to have

**Comment by Lucifer0601code** [comment]
this app just need syncing data with MAL and Anilist and Kitsu. The splash screen is buggy.

**Comment by Lucifer0601code** [comment]
you got discord or any other social media? the app itself is pretty good. make a discord server. add update checking button. if you add discord server, its easy to discuss it
