### ISSUE TITLE
Full Screen With no Screen OS Buttons (Sidebar)??

### ISSUE THREAD

**Issue by MarshMeadow** [Dovakiin0/animeworldz-mobile#6]
It won't go Fullscreen, I still see my buttons to my phone and they won't go away.

**Comment by Dovakiin0** [comment]
Hi @meadow5290, could you provide the brand and type of your mobile phone and a screen shot when in full screen

**Comment by Dovakiin0** [comment]
Hi @meadow5290, the screen shots were unfortunately not uploaded. However I have applied some fixes. Try updating your app and see if the issue is solved.

**Comment by Dovakiin0** [comment]
Glad to hear that. You can close this issue if this solves your problem.
